import { test, expect, Page } from "@playwright/test";

/* ══════════════════════════════════════════════════
   Admin Flow E2E
   Tests login, navigation to content upload, and draft saving.
   ══════════════════════════════════════════════════ */

test.describe("Admin Workflow", () => {
  // Shared login helper to ensure session is active for all tests
  async function performLogin(page: Page) {
    await page.goto("/admin/login");
    await expect(page).toHaveTitle(/Admin Login | Bingeo/i);
    await page.fill('input[type="email"]', "admin@bingeo.com");
    await page.fill('input[type="password"]', "admin123");
    await page.click('button[type="submit"]');
    await expect(page).toHaveURL(/.*admin\/dashboard/);
    await expect(page.locator('h1:has-text("Dashboard")')).toBeVisible();
  }

  test("should login and navigate to content upload", async ({ page }) => {
    await performLogin(page);

    // 4. Navigate to Content Upload via Sidebar (Desktop) or Bottom Nav (Mobile)
    const contentNav = page.getByRole("button", { name: "Content" }).filter({ visible: true });
    await contentNav.click();

    const uploadLink = page.getByRole("link", { name: "Upload" }).filter({ visible: true });
    await uploadLink.click();

    await expect(page).toHaveURL(/.*admin\/content\/upload/);
    await expect(page.getByText(/What are you uploading/i)).toBeVisible();
  });

  test("should complete a basic movie draft flow", async ({ page }) => {
    await performLogin(page);

    // Navigate to Content Upload
    const contentNav = page.getByRole("button", { name: "Content" }).filter({ visible: true });
    await contentNav.click();
    const uploadLink = page.getByRole("link", { name: "Upload" }).filter({ visible: true });
    await uploadLink.click();

    // 1. Select Movie
    await page.click('button:has-text("Movie")');
    await page.click('button:has-text("Next")');

    // 2. Fill Details
    await page.fill('input[id="content-title"]', "E2E Test Movie");
    await page.fill('textarea[id="content-plot"]', "This is a movie generated by an E2E test.");
    await page.click('button:has-text("Action")'); // Genre
    await page.click('button:has-text("Next")');

    // 3. Cast (skip)
    await page.click('button:has-text("Next")');

    // 4. Media upload placeholder
    await expect(page.getByText(/Media Upload/i).first()).toBeVisible();

    // 5. Save Draft
    await page.click('button:has-text("Save Draft")');

    // 6. Verify in Drafts list
    await expect(page).toHaveURL(/.*admin\/content\/drafts/);
    await expect(page.getByText("E2E Test Movie")).toBeVisible();
  });
});
